version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified

    steps:
      - checkout
      # Core
      - run:
          command: dotnet restore .\dotnet-sdk-core\src\main\Reloadly.Core\Reloadly.Core.csproj -p:TargetFrameworks=netstandard2.1
      - run:
          command: dotnet build .\dotnet-sdk-core\src\main\Reloadly.Core\Reloadly.Core.csproj -p:TargetFrameworks=netstandard2.1
      - run:
          command: dotnet test .\dotnet-sdk-core\src\test\Reloadly.Core.Tests.Unit\Reloadly.Core.Tests.Unit.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      # Authentication
      - run:
          command: dotnet restore .\dotnet-sdk-authentication\src\main\Reloadly.Authentication.csproj
      - run:
          command: dotnet build .\dotnet-sdk-authentication\src\main\Reloadly.Authentication.csproj
      - run:
          command: dotnet test .\dotnet-sdk-authentication\src\test\Reloadly.Authentication.Tests.Unit\Reloadly.Authentication.Tests.Unit.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      # Airtime
      - run:
          command: dotnet restore .\dotnet-sdk-airtime\src\main\Reloadly.Airtime.csproj
      - run:
          command: dotnet build .\dotnet-sdk-airtime\src\main\Reloadly.Airtime.csproj
      - run:
          command: dotnet test .\dotnet-sdk-airtime\src\test\Reloadly.Airtime.Tests.Unit\Reloadly.Airtime.Tests.Unit.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
